# Generated by Django 4.1.3 on 2023-11-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_time',
            field=models.IntegerField(null=True),
        ),
    ]
