# Generated by Django 4.2.6 on 2023-12-05 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('selectedLanguage', models.CharField(choices=[('1', 'Python'), ('2', 'C++'), ('3', 'Javascript')], max_length=100)),
                ('level', models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Expert')], max_length=100)),
                ('duration', models.CharField(choices=[('1', '<1 year'), ('2', '1-3 years'), ('3', '>3 years')], max_length=100)),
                ('time', models.IntegerField()),
                ('feid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expertise_id', to='api.expertise')),
            ],
        ),
    ]
