# Generated by Django 4.1.3 on 2023-11-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_question_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='programming_language',
            field=models.CharField(choices=[('1', 'Python'), ('2', 'C++'), ('3', 'Javascript')], max_length=100),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='admin_programming_language',
            field=models.CharField(choices=[('1', 'Python'), ('2', 'C++'), ('3', 'Javascript')], max_length=100),
        ),
    ]
