# Generated by Django 4.2.6 on 2023-12-06 20:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_language_feid_language_fuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='code_image'),
        ),
    ]
