# Generated by Django 4.1.3 on 2023-11-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_expertise_programming_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertise',
            old_name='programming_language',
            new_name='selectedLanguage',
        ),
    ]
