# Generated by Django 4.2.6 on 2024-01-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_code_code_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='selectedLanguage',
            field=models.CharField(choices=[('1', 'Python'), ('2', 'C++'), ('3', 'Javascript'), ('4', 'Java'), ('5', 'Ruby'), ('6', 'Go')], max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='selectedLanguage',
            field=models.CharField(choices=[('1', 'Python'), ('2', 'C++'), ('3', 'Javascript'), ('4', 'Java'), ('5', 'Ruby'), ('6', 'Go')], max_length=100),
        ),
    ]
